/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RequestRouteImport } from './routes/request'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as InNewsRouteImport } from './routes/in-news'
import { Route as GiveRouteImport } from './routes/give'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as TefilinSlugRouteImport } from './routes/tefilin.$slug'
import { Route as EnThankYouLettersRouteImport } from './routes/en.thank-you-letters'
import { Route as EnRabbisAgreementsRouteImport } from './routes/en.rabbis-agreements'
import { Route as EnMediaRouteImport } from './routes/en.media'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const InNewsRoute = InNewsRouteImport.update({
  id: '/in-news',
  path: '/in-news',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const TefilinSlugRoute = TefilinSlugRouteImport.update({
  id: '/tefilin/$slug',
  path: '/tefilin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnThankYouLettersRoute = EnThankYouLettersRouteImport.update({
  id: '/en/thank-you-letters',
  path: '/en/thank-you-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRabbisAgreementsRoute = EnRabbisAgreementsRouteImport.update({
  id: '/en/rabbis-agreements',
  path: '/en/rabbis-agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMediaRoute = EnMediaRouteImport.update({
  id: '/en/media',
  path: '/en/media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/branding': typeof BrandingRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/in-news': typeof InNewsRoute
  '/letters': typeof LettersRoute
  '/request': typeof RequestRoute
  '/stories': typeof StoriesRoute
  '/en/media': typeof EnMediaRoute
  '/en/rabbis-agreements': typeof EnRabbisAgreementsRoute
  '/en/thank-you-letters': typeof EnThankYouLettersRoute
  '/tefilin/$slug': typeof TefilinSlugRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/branding': typeof BrandingRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/in-news': typeof InNewsRoute
  '/letters': typeof LettersRoute
  '/request': typeof RequestRoute
  '/stories': typeof StoriesRoute
  '/en/media': typeof EnMediaRoute
  '/en/rabbis-agreements': typeof EnRabbisAgreementsRoute
  '/en/thank-you-letters': typeof EnThankYouLettersRoute
  '/tefilin/$slug': typeof TefilinSlugRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/branding': typeof BrandingRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/in-news': typeof InNewsRoute
  '/letters': typeof LettersRoute
  '/request': typeof RequestRoute
  '/stories': typeof StoriesRoute
  '/en/media': typeof EnMediaRoute
  '/en/rabbis-agreements': typeof EnRabbisAgreementsRoute
  '/en/thank-you-letters': typeof EnThankYouLettersRoute
  '/tefilin/$slug': typeof TefilinSlugRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreements'
    | '/branding'
    | '/donate'
    | '/give'
    | '/in-news'
    | '/letters'
    | '/request'
    | '/stories'
    | '/en/media'
    | '/en/rabbis-agreements'
    | '/en/thank-you-letters'
    | '/tefilin/$slug'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreements'
    | '/branding'
    | '/donate'
    | '/give'
    | '/in-news'
    | '/letters'
    | '/request'
    | '/stories'
    | '/en/media'
    | '/en/rabbis-agreements'
    | '/en/thank-you-letters'
    | '/tefilin/$slug'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/agreements'
    | '/branding'
    | '/donate'
    | '/give'
    | '/in-news'
    | '/letters'
    | '/request'
    | '/stories'
    | '/en/media'
    | '/en/rabbis-agreements'
    | '/en/thank-you-letters'
    | '/tefilin/$slug'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementsRoute: typeof AgreementsRoute
  BrandingRoute: typeof BrandingRoute
  DonateRoute: typeof DonateRoute
  GiveRoute: typeof GiveRoute
  InNewsRoute: typeof InNewsRoute
  LettersRoute: typeof LettersRoute
  RequestRoute: typeof RequestRoute
  StoriesRoute: typeof StoriesRoute
  EnMediaRoute: typeof EnMediaRoute
  EnRabbisAgreementsRoute: typeof EnRabbisAgreementsRoute
  EnThankYouLettersRoute: typeof EnThankYouLettersRoute
  TefilinSlugRoute: typeof TefilinSlugRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-news': {
      id: '/in-news'
      path: '/in-news'
      fullPath: '/in-news'
      preLoaderRoute: typeof InNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tefilin/$slug': {
      id: '/tefilin/$slug'
      path: '/tefilin/$slug'
      fullPath: '/tefilin/$slug'
      preLoaderRoute: typeof TefilinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/thank-you-letters': {
      id: '/en/thank-you-letters'
      path: '/en/thank-you-letters'
      fullPath: '/en/thank-you-letters'
      preLoaderRoute: typeof EnThankYouLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/rabbis-agreements': {
      id: '/en/rabbis-agreements'
      path: '/en/rabbis-agreements'
      fullPath: '/en/rabbis-agreements'
      preLoaderRoute: typeof EnRabbisAgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/media': {
      id: '/en/media'
      path: '/en/media'
      fullPath: '/en/media'
      preLoaderRoute: typeof EnMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementsRoute: AgreementsRoute,
  BrandingRoute: BrandingRoute,
  DonateRoute: DonateRoute,
  GiveRoute: GiveRoute,
  InNewsRoute: InNewsRoute,
  LettersRoute: LettersRoute,
  RequestRoute: RequestRoute,
  StoriesRoute: StoriesRoute,
  EnMediaRoute: EnMediaRoute,
  EnRabbisAgreementsRoute: EnRabbisAgreementsRoute,
  EnThankYouLettersRoute: EnThankYouLettersRoute,
  TefilinSlugRoute: TefilinSlugRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
