/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492RouteImport } from './routes/מכתבי-תודה'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as InNewsRouteImport } from './routes/in-news'
import { Route as GiveRouteImport } from './routes/give'
import { Route as EnRouteImport } from './routes/en'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TefilinSlugRouteImport } from './routes/tefilin.$slug'
import { Route as EnTheTefillinTieInitiativeRouteImport } from './routes/en.the-tefillin-tie-initiative'
import { Route as EnThankYouLettersRouteImport } from './routes/en.thank-you-letters'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as EnSupportAndDonationRouteImport } from './routes/en.support-and-donation'
import { Route as EnStories2RouteImport } from './routes/en.stories-2'
import { Route as EnRequestToDonateTefillinRouteImport } from './routes/en.request-to-donate-tefillin'
import { Route as EnRequestForTefillinRouteImport } from './routes/en.request-for-tefillin'
import { Route as EnRabbisAgreementsRouteImport } from './routes/en.rabbis-agreements'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnArticlesInTheMediaRouteImport } from './routes/en.articles-in-the-media'
import { Route as EnAccessibilityRouteImport } from './routes/en.accessibility'
import { Route as AdminMigrateRouteImport } from './routes/admin.migrate'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as EnTefilinSlugRouteImport } from './routes/en.tefilin.$slug'

const Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route =
  Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492RouteImport.update(
    {
      id: '/מכתבי-תודה',
      path: '/מכתבי-תודה',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const InNewsRoute = InNewsRouteImport.update({
  id: '/in-news',
  path: '/in-news',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TefilinSlugRoute = TefilinSlugRouteImport.update({
  id: '/tefilin/$slug',
  path: '/tefilin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTheTefillinTieInitiativeRoute =
  EnTheTefillinTieInitiativeRouteImport.update({
    id: '/the-tefillin-tie-initiative',
    path: '/the-tefillin-tie-initiative',
    getParentRoute: () => EnRoute,
  } as any)
const EnThankYouLettersRoute = EnThankYouLettersRouteImport.update({
  id: '/thank-you-letters',
  path: '/thank-you-letters',
  getParentRoute: () => EnRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRoute,
} as any)
const EnSupportAndDonationRoute = EnSupportAndDonationRouteImport.update({
  id: '/support-and-donation',
  path: '/support-and-donation',
  getParentRoute: () => EnRoute,
} as any)
const EnStories2Route = EnStories2RouteImport.update({
  id: '/stories-2',
  path: '/stories-2',
  getParentRoute: () => EnRoute,
} as any)
const EnRequestToDonateTefillinRoute =
  EnRequestToDonateTefillinRouteImport.update({
    id: '/request-to-donate-tefillin',
    path: '/request-to-donate-tefillin',
    getParentRoute: () => EnRoute,
  } as any)
const EnRequestForTefillinRoute = EnRequestForTefillinRouteImport.update({
  id: '/request-for-tefillin',
  path: '/request-for-tefillin',
  getParentRoute: () => EnRoute,
} as any)
const EnRabbisAgreementsRoute = EnRabbisAgreementsRouteImport.update({
  id: '/rabbis-agreements',
  path: '/rabbis-agreements',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnRoute,
} as any)
const EnArticlesInTheMediaRoute = EnArticlesInTheMediaRouteImport.update({
  id: '/articles-in-the-media',
  path: '/articles-in-the-media',
  getParentRoute: () => EnRoute,
} as any)
const EnAccessibilityRoute = EnAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => EnRoute,
} as any)
const AdminMigrateRoute = AdminMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const EnTefilinSlugRoute = EnTefilinSlugRouteImport.update({
  id: '/tefilin/$slug',
  path: '/tefilin/$slug',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/agreements': typeof AgreementsRoute
  '/branding': typeof BrandingRoute
  '/donate': typeof DonateRoute
  '/en': typeof EnRouteWithChildren
  '/give': typeof GiveRoute
  '/in-news': typeof InNewsRoute
  '/letters': typeof LettersRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/מכתבי-תודה': typeof Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/en/accessibility': typeof EnAccessibilityRoute
  '/en/articles-in-the-media': typeof EnArticlesInTheMediaRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/rabbis-agreements': typeof EnRabbisAgreementsRoute
  '/en/request-for-tefillin': typeof EnRequestForTefillinRoute
  '/en/request-to-donate-tefillin': typeof EnRequestToDonateTefillinRoute
  '/en/stories-2': typeof EnStories2Route
  '/en/support-and-donation': typeof EnSupportAndDonationRoute
  '/en/terms': typeof EnTermsRoute
  '/en/thank-you-letters': typeof EnThankYouLettersRoute
  '/en/the-tefillin-tie-initiative': typeof EnTheTefillinTieInitiativeRoute
  '/tefilin/$slug': typeof TefilinSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/tefilin/$slug': typeof EnTefilinSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/agreements': typeof AgreementsRoute
  '/branding': typeof BrandingRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/in-news': typeof InNewsRoute
  '/letters': typeof LettersRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/מכתבי-תודה': typeof Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/en/accessibility': typeof EnAccessibilityRoute
  '/en/articles-in-the-media': typeof EnArticlesInTheMediaRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/rabbis-agreements': typeof EnRabbisAgreementsRoute
  '/en/request-for-tefillin': typeof EnRequestForTefillinRoute
  '/en/request-to-donate-tefillin': typeof EnRequestToDonateTefillinRoute
  '/en/stories-2': typeof EnStories2Route
  '/en/support-and-donation': typeof EnSupportAndDonationRoute
  '/en/terms': typeof EnTermsRoute
  '/en/thank-you-letters': typeof EnThankYouLettersRoute
  '/en/the-tefillin-tie-initiative': typeof EnTheTefillinTieInitiativeRoute
  '/tefilin/$slug': typeof TefilinSlugRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
  '/en/tefilin/$slug': typeof EnTefilinSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/agreements': typeof AgreementsRoute
  '/branding': typeof BrandingRoute
  '/donate': typeof DonateRoute
  '/en': typeof EnRouteWithChildren
  '/give': typeof GiveRoute
  '/in-news': typeof InNewsRoute
  '/letters': typeof LettersRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/מכתבי-תודה': typeof Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/en/accessibility': typeof EnAccessibilityRoute
  '/en/articles-in-the-media': typeof EnArticlesInTheMediaRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/rabbis-agreements': typeof EnRabbisAgreementsRoute
  '/en/request-for-tefillin': typeof EnRequestForTefillinRoute
  '/en/request-to-donate-tefillin': typeof EnRequestToDonateTefillinRoute
  '/en/stories-2': typeof EnStories2Route
  '/en/support-and-donation': typeof EnSupportAndDonationRoute
  '/en/terms': typeof EnTermsRoute
  '/en/thank-you-letters': typeof EnThankYouLettersRoute
  '/en/the-tefillin-tie-initiative': typeof EnTheTefillinTieInitiativeRoute
  '/tefilin/$slug': typeof TefilinSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/tefilin/$slug': typeof EnTefilinSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/admin'
    | '/agreements'
    | '/branding'
    | '/donate'
    | '/en'
    | '/give'
    | '/in-news'
    | '/letters'
    | '/privacy'
    | '/request'
    | '/stories'
    | '/terms'
    | '/מכתבי-תודה'
    | '/admin/leads'
    | '/admin/migrate'
    | '/en/accessibility'
    | '/en/articles-in-the-media'
    | '/en/privacy'
    | '/en/rabbis-agreements'
    | '/en/request-for-tefillin'
    | '/en/request-to-donate-tefillin'
    | '/en/stories-2'
    | '/en/support-and-donation'
    | '/en/terms'
    | '/en/thank-you-letters'
    | '/en/the-tefillin-tie-initiative'
    | '/tefilin/$slug'
    | '/admin/'
    | '/en/'
    | '/en/tefilin/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/agreements'
    | '/branding'
    | '/donate'
    | '/give'
    | '/in-news'
    | '/letters'
    | '/privacy'
    | '/request'
    | '/stories'
    | '/terms'
    | '/מכתבי-תודה'
    | '/admin/leads'
    | '/admin/migrate'
    | '/en/accessibility'
    | '/en/articles-in-the-media'
    | '/en/privacy'
    | '/en/rabbis-agreements'
    | '/en/request-for-tefillin'
    | '/en/request-to-donate-tefillin'
    | '/en/stories-2'
    | '/en/support-and-donation'
    | '/en/terms'
    | '/en/thank-you-letters'
    | '/en/the-tefillin-tie-initiative'
    | '/tefilin/$slug'
    | '/admin'
    | '/en'
    | '/en/tefilin/$slug'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/admin'
    | '/agreements'
    | '/branding'
    | '/donate'
    | '/en'
    | '/give'
    | '/in-news'
    | '/letters'
    | '/privacy'
    | '/request'
    | '/stories'
    | '/terms'
    | '/מכתבי-תודה'
    | '/admin/leads'
    | '/admin/migrate'
    | '/en/accessibility'
    | '/en/articles-in-the-media'
    | '/en/privacy'
    | '/en/rabbis-agreements'
    | '/en/request-for-tefillin'
    | '/en/request-to-donate-tefillin'
    | '/en/stories-2'
    | '/en/support-and-donation'
    | '/en/terms'
    | '/en/thank-you-letters'
    | '/en/the-tefillin-tie-initiative'
    | '/tefilin/$slug'
    | '/admin/'
    | '/en/'
    | '/en/tefilin/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgreementsRoute: typeof AgreementsRoute
  BrandingRoute: typeof BrandingRoute
  DonateRoute: typeof DonateRoute
  EnRoute: typeof EnRouteWithChildren
  GiveRoute: typeof GiveRoute
  InNewsRoute: typeof InNewsRoute
  LettersRoute: typeof LettersRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route: typeof Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route
  TefilinSlugRoute: typeof TefilinSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/מכתבי-תודה': {
      id: '/מכתבי-תודה'
      path: '/מכתבי-תודה'
      fullPath: '/מכתבי-תודה'
      preLoaderRoute: typeof Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-news': {
      id: '/in-news'
      path: '/in-news'
      fullPath: '/in-news'
      preLoaderRoute: typeof InNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tefilin/$slug': {
      id: '/tefilin/$slug'
      path: '/tefilin/$slug'
      fullPath: '/tefilin/$slug'
      preLoaderRoute: typeof TefilinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/the-tefillin-tie-initiative': {
      id: '/en/the-tefillin-tie-initiative'
      path: '/the-tefillin-tie-initiative'
      fullPath: '/en/the-tefillin-tie-initiative'
      preLoaderRoute: typeof EnTheTefillinTieInitiativeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/thank-you-letters': {
      id: '/en/thank-you-letters'
      path: '/thank-you-letters'
      fullPath: '/en/thank-you-letters'
      preLoaderRoute: typeof EnThankYouLettersRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/support-and-donation': {
      id: '/en/support-and-donation'
      path: '/support-and-donation'
      fullPath: '/en/support-and-donation'
      preLoaderRoute: typeof EnSupportAndDonationRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/stories-2': {
      id: '/en/stories-2'
      path: '/stories-2'
      fullPath: '/en/stories-2'
      preLoaderRoute: typeof EnStories2RouteImport
      parentRoute: typeof EnRoute
    }
    '/en/request-to-donate-tefillin': {
      id: '/en/request-to-donate-tefillin'
      path: '/request-to-donate-tefillin'
      fullPath: '/en/request-to-donate-tefillin'
      preLoaderRoute: typeof EnRequestToDonateTefillinRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/request-for-tefillin': {
      id: '/en/request-for-tefillin'
      path: '/request-for-tefillin'
      fullPath: '/en/request-for-tefillin'
      preLoaderRoute: typeof EnRequestForTefillinRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/rabbis-agreements': {
      id: '/en/rabbis-agreements'
      path: '/rabbis-agreements'
      fullPath: '/en/rabbis-agreements'
      preLoaderRoute: typeof EnRabbisAgreementsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/articles-in-the-media': {
      id: '/en/articles-in-the-media'
      path: '/articles-in-the-media'
      fullPath: '/en/articles-in-the-media'
      preLoaderRoute: typeof EnArticlesInTheMediaRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/accessibility': {
      id: '/en/accessibility'
      path: '/accessibility'
      fullPath: '/en/accessibility'
      preLoaderRoute: typeof EnAccessibilityRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/migrate': {
      id: '/admin/migrate'
      path: '/migrate'
      fullPath: '/admin/migrate'
      preLoaderRoute: typeof AdminMigrateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/tefilin/$slug': {
      id: '/en/tefilin/$slug'
      path: '/tefilin/$slug'
      fullPath: '/en/tefilin/$slug'
      preLoaderRoute: typeof EnTefilinSlugRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMigrateRoute: typeof AdminMigrateRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMigrateRoute: AdminMigrateRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnAccessibilityRoute: typeof EnAccessibilityRoute
  EnArticlesInTheMediaRoute: typeof EnArticlesInTheMediaRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnRabbisAgreementsRoute: typeof EnRabbisAgreementsRoute
  EnRequestForTefillinRoute: typeof EnRequestForTefillinRoute
  EnRequestToDonateTefillinRoute: typeof EnRequestToDonateTefillinRoute
  EnStories2Route: typeof EnStories2Route
  EnSupportAndDonationRoute: typeof EnSupportAndDonationRoute
  EnTermsRoute: typeof EnTermsRoute
  EnThankYouLettersRoute: typeof EnThankYouLettersRoute
  EnTheTefillinTieInitiativeRoute: typeof EnTheTefillinTieInitiativeRoute
  EnIndexRoute: typeof EnIndexRoute
  EnTefilinSlugRoute: typeof EnTefilinSlugRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAccessibilityRoute: EnAccessibilityRoute,
  EnArticlesInTheMediaRoute: EnArticlesInTheMediaRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnRabbisAgreementsRoute: EnRabbisAgreementsRoute,
  EnRequestForTefillinRoute: EnRequestForTefillinRoute,
  EnRequestToDonateTefillinRoute: EnRequestToDonateTefillinRoute,
  EnStories2Route: EnStories2Route,
  EnSupportAndDonationRoute: EnSupportAndDonationRoute,
  EnTermsRoute: EnTermsRoute,
  EnThankYouLettersRoute: EnThankYouLettersRoute,
  EnTheTefillinTieInitiativeRoute: EnTheTefillinTieInitiativeRoute,
  EnIndexRoute: EnIndexRoute,
  EnTefilinSlugRoute: EnTefilinSlugRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  AgreementsRoute: AgreementsRoute,
  BrandingRoute: BrandingRoute,
  DonateRoute: DonateRoute,
  EnRoute: EnRouteWithChildren,
  GiveRoute: GiveRoute,
  InNewsRoute: InNewsRoute,
  LettersRoute: LettersRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route:
    Char1502Char1499Char1514Char1489Char1497Char1514Char1493Char1491Char1492Route,
  TefilinSlugRoute: TefilinSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
